require_relative 'tasks/clean'
require_relative 'tasks/download'
require_relative 'tasks/extract'
require_relative 'tasks/install'
require_relative 'tasks/fetch'
require_relative 'tasks/ensure'
require_relative 'tasks/all'
